services:
  - type: web
    name: igrocery-server
    runtime: node
    rootDir: server
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
